toluaina/pgsync

pgsync/sync.py
This addresses the newest issue in #96 where `_type` was an array because of a comma after the value.
=> _type should be a string, not an array

pgsync/elastichelper.py
When using Elasticsearch < 7, the mappings needs to contain a `_doc` object which is currently missing. This addresses an issue bootstrapping when using the `mapping` functionality of `transform`.
=> Adds _doc to the mappings when using ES < 7

pgsync/base.py
Addresses the `oid` issue for those of us using PostgreSQL < 12 the same way you've addressed the issue for `xmin`. Fixes #107.
=> Fixes an issue where `oid` isn't included in the reflection by sqlalchemy for PostgreSQL < 12

pgsync/constants.py, pgsync/elastichelper.py
I originally started working on this because I needed a way to add the `ignore_above` mapping parameter for my project but there are many other [mapping parameters](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-params.html) so I decided to add support for all of them.
=> Adds support for all mapping parameters

pgsync/constants.py
We have an unusual database schema which contains a dash and that wasn't supported by `LOGICAL_SLOT_PREFIX` so fixed that. I also added support for `"` around the schema since that was also missing.
=> Adds support for schemas and tables with dashes

pgsync/base.py, pgsync/sync.py, pgsync/view.py
A schema was not provided when creating the new materialized views which caused `psycopg2.errors.DuplicateTable: relation "_pkey_view" already exists` errors for those of us with multiple database schemas. I've addressed issue #108 by adding the schema in the queries.
=> Addresses an issue where multiple schemas caused duplicate materialized view errors

pgsync/base.py
Not everyone uses citext, but we do. Rather than making it a requirement/dependency, I added optional support for citext and geoalchemy2 if they were manually installed.
This remove warnings such as: `SAWarning: Did not recognize type 'citext' of column`.
=> Adds optional support for citext and geoalchemy2

pgsync/elastichelper.py, pgsync/sync.py
We use routing for one of our large indices. This adds support for the [`_routing`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html) metadata field.
This works by letting a PGSync user specify which field should be used for routing in the schema file. For example:
```json
[
{
"database": "twitter",
"index": "tweets",
"routing": "user_id",
...
}
]
```
When `routing` is specified, the `_routing` option is included when creating the schema, and in all bulk calls.
=> Adds support for routing

.env.sample, pgsync/redisqueue.py, pgsync/settings.py, pgsync/utils.py
We use TLS with Redis so we need to use `rediss` instead of `redis` as the scheme when connecting. This adds a `REDIS_SCHEME` environment variable which default to `redis` for those of us that use TLS. I chose this way so that it's consistent with how it's done for Elasticsearch.
=> Rediss support

pgsync/elastichelper.py
Incase of AWS hosted elasticsearch we don't have to use the parsed url for constructing the connection, we can directly use the ELASTICSEARCH_HOST variable
=> Use ELASTICSEARCH_HOST value instead of parsed url in connection

setup.py
When I tried to run the step `python setup.py develop` mentioned in the contribution docs it was throwing the following error
```
Traceback (most recent call last):
File "/Users/harishsreeramappa/Desktop/projects/pgsync/setup.py", line 28, in <module>
VERSION = get_version()
File "/Users/harishsreeramappa/Desktop/projects/pgsync/setup.py", line 18, in get_version
return re.search(pattern, contents, re.MULTILINE).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
You can also check the publish action https://github.com/toluaina/pgsync/runs/2778103648?check_suite_focus=true
=> Fix the regex used for matching the version

pgsync/sync.py
If my database has upper case symbols `bootstrap` gives an error: `HINT:  Replication slot names may only contain lower case letters, numbers, and the underscore character.`, wich arises in `create_replication_slot` function.
I suggest decoupling the database and replication slot names.
but I haven't researched the entire source code, so I'm not sure if the change I proposed won't break something else. Please check and, if everything is good, I will be glad to see my proposed feature in the nearest release.
=> Fix "Replication slot names may only contain lower case letters, numbers, and the underscore character."

pgsync/constants.py
Please merge this as search_as_you_type is supported in elasticsearch field types. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-as-you-type.html
=> Added search_as_you_type value in ELASTICSEARCH_TYPES

pgsync/settings.py, pgsync/sync.py
- Adds the `REDIS_WRITE_CHUNK_SIZE` environment variable which allows pushes to the redis queue to be batched
In reference to #233 I wanted to propose a solution to slow syncs between the database and redis. I was able to get the sync time down from ~2 minutes to 1 minute when inserting ~16k items on my local machine, with a single core dedicated to the process. I think we would see greater improvements on a more powerful computer.
Would love any feedback on this option and your help in verifying it works.
=> batching redis writes

pgsync/settings.py
In the current project, when using pypi to execute the script, `.env` file will not search start at current path but the bin path.
example:
bootstrap in  `/path/to/python/bin/bootstrap`
current path in  `/user/current/path`
The package `environs` will start to search `.env` from `/path/to/python/bin` ->  `/path/to/python/` ->  `/path/to/` ->  `/path/` ->  `/`
If using source code project, it's not a problem. Because scripts is in the project and `.env` file also in project root path.
But when using pypi, it is not. 
So, I think add a parameter to let `environs` start search at current path is a option.
=> Search `.env` file from current folder, not the executable script folder

pgsync/sync.py
Just upgraded to 2.3.2 and got the following fatal error:
```
Exception in poll_redis() for thread Thread-94: 'Sync' object has no attribute 'materialized_views'
```
This was the only place in the code that matched.  It looks like this is a simple typo in converting from `self.materialized` to `self._materialized_views`.  There should be an underscore.  Thank you for developing this library.
=> Typo in Sync._refresh_views

pgsync/base.py, tests/test_base.py
Running `—analyze` errors in python 3.11 when indices exist
```bash
File "/Users/lorensiebert/workspace/pgsync/pgsync/base.py", line 252, in indices
self.__indices[(table, schema)] = sorted(
^^^^^^^
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
=> Fix call to `sorted()` on dicts

pgsync/base.py
I saw some evidence via Fil that memory usage spikes when truncating a slot with many txs in it.
I think under the hood, a call to `execute` without `stream_results` will cause psycopg2 to pull down results and instantiate them in memory even though they are unused.
With this change in place, I was able to process a bulk update that failed 100% of the time. Instead of RSS spiking to 3.0GB, it stayed constant at 110MB.
It's very difficult to replicate this, and I'm not completely confident this fixes the issue entirely. I almost wonder if the safer thing to do is have `pg_logical_slot_get_changes` loop through blocks of say `LOGICAL_SLOT_CHUNK_SIZE` so we're guaranteed not to ever return too large a payload.
=> Use STREAM_RESULTS in call to execute

pgsync/querybuilder.py
Tests pass, for additional info, please refer to the issue https://github.com/toluaina/pgsync/issues/397
=> Fix for a certain failing relationship layout, fixes https://github.com/toluaina/pgsync/issues/397

pgsync/transform.py
* About the indentation change: seems like just a typo, but in some cases causes `KeyError` (when for example, the second `key` has empty `value` -- like for a through table without own primary key).
* About the removed line: doesn't seem to be doing anything.
=> Fix `get_primary_keys`

pgsync/search_client.py, pgsync/settings.py
Adds support for AWS Opensearch Serverless, which requires the service name `aoss` instead of `es` when instantiating the search client. 
Users must set the `OPENSEARCH_AWS_SERVERLESS` environment variable to `true` to allow the proper search client configuration.
Reference: https://github.com/opensearch-project/opensearch-py/blob/main/guides/auth.md
=> Support AWS OpenSearch Serverless

pgsync/constants.py
Bugfix for replication regex to parse double values served like 2.3e+09, seems to be working fine for me, propably requires some more testing  
fixes #527
=> Fixes #527: Bugfix LOGICAL_SLOT_SUFFIX regex

Dockerfile, docker-compose.yml, docker/runserver.sh
- adds kibana to the elasticsearch docker compose file
- add optional docker build arg EXAMPLE_NAME to select which test folder to select
=> docker compose: add kibana and add optional EXAMPLE_NAME build arg to select example

pgsync/search_client.py
AWS-hosted environments can't use the custom Elasticsearch timeouts because when creating the search clients these are not receiving the `timeout=settings.ELASTICSEARCH_TIMEOUT` argument. This makes longer-running requests fail when they hit the default 10-second timeout.
=> Adds ELASTICSEARCH_TIMEOUT to all search clients

pgsync/constants.py
Currently, the logical slot suffix restricts values by disallowing spaces, permitting only word characters, single quotes, double quotes, hyphens, dots, and plus signs. However, values can also include spaces. For instance, the _title_ column often contains values with multiple words separated by spaces. Hence, we need to adjust the logic to incorporate **spaces** in values.
=> Update regex to add values with space characters also

pgsync/search_client.py
In trying to debug an issue, I needed to add more logging to PGSync in order to see the problem. This PR adds additional logging similar to [this one](https://discuss.elastic.co/t/helpers-parallel-bulk-in-python-not-working/39498/2) within the Elasticsearch community.
Before, I would see messages like:
```
BulkIndexError: ('1 document(s) failed to index.')
```
While this did indicate something was wrong with the document, I did not know which one or why it was problematic. With this change, I now see errors containing:
```
{..., 'reason': 'Document contains at least one immense term in field="description" ...}
```
This along with additional information (such as the document shape (including `id`) have been valuable information.
**Note**: This logging will only be visible with …
=> Add More Error Logging When Indexing Fails

pgsync/settings.py, pgsync/urls.py
This new feature allows users to specify a custom username for the Redis connection in PgSync. Previously, PgSync relied solely on the default Redis user. With this update, users can now provide their own Redis username, enhancing flexibility and security. One can provide the username via REDIS_USER environment variable.
=> Add Custom Username Support for Redis Connection in PgSync
